openapi: "3.0.0"
info:
  description: REST API for de_exercise.
  version: "1.0.0"
  title: REST API for de_exercise.

servers:
  - url: /api

paths:
  /exercise/get_document:
    get:
      operationId: api.exercise.get_document
      tags:
        - Exercise
      summary: Get a document exercise.
      description: Get a document exercise.
      parameters:
        - name: document_title
          in: query
          description: Title of document.
          schema:
            type: string
          required: True
        - name: ex_types
          in: query
          description: Type of exercises to get.
          schema:
            type: array
            items:
              type: string
          required: False
      responses:
        200:
          description: Successfully returned a document exercise.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exercises'

  /exercise/get_paragraph:
    get:
      operationId: api.exercise.get_paragraph
      tags:
        - Exercise
      summary: Get a paragraph exercise.
      description: Get a paragraph exercise.
      parameters:
        - name: document_title
          in: query
          description: Title of document.
          schema:
            type: string
          required: True
        - name: paragraph_index
          in: query
          description: Paragraph number to get.
          schema:
            type: integer
          required: True
        - name: ex_types
          in: query
          description: Type of exercises to get.
          schema:
            type: array
            items:
              type: string
          required: False
      responses:
        200:
          description: Successfully returned a paragraph exercise.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exercises'

  /exercise/get_document_list:
    get:
      operationId: api.exercise.get_document_list
      tags:
        - Exercise
      summary: Get a list of all the distinct document titles.
      description: Get a list of all the distinct document titles.
      responses:
        200:
          description: Successfully returned a list of document titles.
          content:
            application/json:
              schema:
                type: array
                items: {}

  /exercise/get_ex_type_list:
    get:
      operationId: api.exercise.get_ex_type_list
      tags:
        - Exercise
      summary: Get a list of all the distinct exercise types.
      description: Get a list of all the distinct exercise types.
      parameters:
        - name: document_title
          in: query
          description: Title of document that exercises are on.
          schema:
            type: string
          required: True
      responses:
        200:
          description: Successfully returned a list of exercise types.
          content:
            application/json:
              schema:
                type: array
                items: {}

  /exercise/put_document:
    put:
      operationId: api.exercise.put_document
      tags:
        - Exercise
      summary: Add a text file in German to make as an exercise.
      description: Add a text file in German to make as an exercise.
      parameters:
        - name: document_title
          in: query
          description: Title of document.
          schema:
            type: string
          required: True
        - name: document_author
          in: query
          description: Author of document.
          schema:
            type: string
          required: True
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: text
      responses:
        201:
          description: Successfully created exercises from the document.

components:
  schemas:
    topic_word:
      properties:
        text:
          type: string
        lemma:
          type: string
        pos:
          type: string
        index:
          type: integer
        type:
          type: string
        feats:
          type: array
          items: {}
    exercise:
      properties:
        document_title:
          type: string
        paragraph_start:
          type: string
        paragraph_index:
          type: integer
        sentence_index:
          type: integer
        sentence_text:
          type: string
        schema:
          type: array
          items:
            $ref: "#/components/schemas/topic_word"
    exercises:
      type: array
      items:
        $ref: "#/components/schemas/exercise"

