dev:
    api_routes:                                                                                                 
        nlp_json:
            process_sentences_url: 'http://localhost:5010/api/process_sentences'

    port:                           5011
    mongo_uri:                      'mongodb://localhost:27017/fehlendewoerter'

prod:
    api_routes:                                                                                                 
        nlp_json:
            process_sentences_url: 'http://localhost:5010/api/process_sentences'

    port:                           5011
    mongo_uri:                      'mongodb://localhost:27017/fehlendewoerter'
